/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/UnityWebGL`; params?: Router.UnknownInputParams; } | { pathname: `/signinup/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signinup/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/SocketContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mode` | `/mode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settingsPage/analysis`; params?: Router.UnknownInputParams; } | { pathname: `/settingsPage/bluetooth`; params?: Router.UnknownInputParams; } | { pathname: `/settingsPage/wifi`; params?: Router.UnknownInputParams; } | { pathname: `/trainingPage/led`; params?: Router.UnknownInputParams; } | { pathname: `/trainingPage/training`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/UnityWebGL`; params?: Router.UnknownOutputParams; } | { pathname: `/signinup/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/signinup/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/SocketContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mode` | `/mode`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/settingsPage/analysis`; params?: Router.UnknownOutputParams; } | { pathname: `/settingsPage/bluetooth`; params?: Router.UnknownOutputParams; } | { pathname: `/settingsPage/wifi`; params?: Router.UnknownOutputParams; } | { pathname: `/trainingPage/led`; params?: Router.UnknownOutputParams; } | { pathname: `/trainingPage/training`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/UnityWebGL${`?${string}` | `#${string}` | ''}` | `/signinup/signin${`?${string}` | `#${string}` | ''}` | `/signinup/signup${`?${string}` | `#${string}` | ''}` | `/../contexts/SocketContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mode${`?${string}` | `#${string}` | ''}` | `/mode${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/settingsPage/analysis${`?${string}` | `#${string}` | ''}` | `/settingsPage/bluetooth${`?${string}` | `#${string}` | ''}` | `/settingsPage/wifi${`?${string}` | `#${string}` | ''}` | `/trainingPage/led${`?${string}` | `#${string}` | ''}` | `/trainingPage/training${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/UnityWebGL`; params?: Router.UnknownInputParams; } | { pathname: `/signinup/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signinup/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/SocketContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mode` | `/mode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settingsPage/analysis`; params?: Router.UnknownInputParams; } | { pathname: `/settingsPage/bluetooth`; params?: Router.UnknownInputParams; } | { pathname: `/settingsPage/wifi`; params?: Router.UnknownInputParams; } | { pathname: `/trainingPage/led`; params?: Router.UnknownInputParams; } | { pathname: `/trainingPage/training`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
